
BUILDIN_DEF(csvgetrows, "s"),
BUILDIN_DEF(csvgetcols, "si"),
BUILDIN_DEF(csvread, "sii"),
BUILDIN_DEF(csvreadrow, "sis"),
BUILDIN_DEF(csvreadcol, "sis"),
BUILDIN_DEF(csvwrite, "siis"),
BUILDIN_DEF(csvwritearray, "sis"),
BUILDIN_DEF(csvfind, "sis"),
BUILDIN_DEF(csvreload, "s"),
BUILDIN_DEF(csvinsert, "si"),
BUILDIN_DEF(csvdelete, "si"),
BUILDIN_DEF(csvsort, "sii"),
BUILDIN_DEF(csvflush, "s"),
