BUILDIN_DEF(allowuseitem, "?"),
BUILDIN_DEF(areakillmonster, "siiii"),
BUILDIN_DEF(areamisceffect, "siiiii"),
BUILDIN_DEF(areamobuseskill2,"siiiiiviiiii"),
BUILDIN_DEF(areasetcell, "siiiii"),
BUILDIN_DEF(areasoundeffect, "siiiisi?"),
BUILDIN_DEF(checkdead, ""),
BUILDIN_DEF(checkitemblank, ""),
BUILDIN_DEF(checkquest2, "i"),
BUILDIN_DEF(chgquest, "ii"),
BUILDIN_DEF(compquest, "i?"),
BUILDIN_DEF(delequip2, "i"),
BUILDIN_DEF(delquest, "i?"),
BUILDIN_DEF(distance2, "i?"),
BUILDIN_DEF(downrefitem2, "i?"),
BUILDIN_DEF(dropitem, "siivii?"),
BUILDIN_DEF(equippeditem, "i?"),
BUILDIN_DEF(failedrefitem2, "i?"),
BUILDIN_DEF(failedrefitem3, "i?"),
BUILDIN_DEF(failedrefitem4, "i?"),
BUILDIN_DEF(failedremovecards2,"ii"),
BUILDIN_DEF(getareamobs, "siiii?"),
BUILDIN_DEF(getbaseclass, "i?"),
BUILDIN_DEF(getequipcardcnt2,"i"),
BUILDIN_DEF(getequipcardid2,"ii"),
BUILDIN_DEF(getequipid2, "i"),
BUILDIN_DEF(getequipisenableref2, "i"),
BUILDIN_DEF(getequipisequiped2, "i"),
BUILDIN_DEF(getequipisidentify, "i"),
BUILDIN_DEF(getequipname2, "i"),
BUILDIN_DEF(getequippercentrefinery2, "i?"),
BUILDIN_DEF(getequiprefinerycnt2, "i"),
BUILDIN_DEF(getequipweaponlv2, "i"),
BUILDIN_DEF(getmapmobs, "s?"),
BUILDIN_DEF(getmapname, "s"),
BUILDIN_DEF(getmdmapname, "s"),
BUILDIN_DEF(getmdnpcname, "s"),
BUILDIN_DEF(getonlinepartymember, "?"),
BUILDIN_DEF(getrepairableitemcount, ""),
BUILDIN_DEF(getwaitingpcid, "r?"),
BUILDIN_DEF(mdcreate, "s"),
BUILDIN_DEF(mdenter, "s"),
BUILDIN_DEF(npcskillsupport, "ii??"),
BUILDIN_DEF(openbook, "i?"),
BUILDIN_DEF(printarray, "r?"),
BUILDIN_DEF(repairitem, ""),
BUILDIN_DEF(sc_ison, "i"),
BUILDIN_DEF(sc_start3, "iiiiiii?"),
BUILDIN_DEF(strstr, "ss"),
BUILDIN_DEF(substr2, "sii"),
BUILDIN_DEF(successrefitem2, "i?"),
BUILDIN_DEF(successremovecards2,"i"),
BUILDIN_DEF(callmonster,"siisi???"),
